{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:BlockTest", "name": "test_check_pow", "time": 0.0002696514129638672, "type": "error", "errtype": "builtins.TypeError", "message": "'<' not supported between instances of 'int' and 'method'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/adamjonas/proof-of-work-jsong-pb-denver-070918/test/index_test.py\", line 10, in test_check_pow\n    self.assertTrue(block.check_pow())\n  File \"/home/adamjonas/proof-of-work-jsong-pb-denver-070918/index.ipynb\", line 61, in check_pow\n    \"# check proof of work < target\\n\",\nTypeError: '<' not supported between instances of 'int' and 'method'\n"}]}